Repository silver-plate/SilverPlate-BE, pull requests merged in 2023-12, with the labels that each got.

#5 feat: entity setting
  src/main/java/com/plate/silverplate/SilverPlateApplication.java
  src/main/java/com/plate/silverplate/common/entity/BaseTimeEntity.java
  src/main/java/com/plate/silverplate/domain/Battle.java
  src/main/java/com/plate/silverplate/domain/BattleHistory.java
  src/main/java/com/plate/silverplate/domain/Favorite.java
  src/main/java/com/plate/silverplate/domain/FoodRegistration.java
  src/main/java/com/plate/silverplate/domain/Meal.java
  src/main/java/com/plate/silverplate/domain/MealDailyScore.java
  src/main/java/com/plate/silverplate/domain/MealList.java
  src/main/java/com/plate/silverplate/domain/NutritionFact.java
  src/main/java/com/plate/silverplate/domain/Registration.java
  src/main/java/com/plate/silverplate/domain/User.java
  src/main/java/com/plate/silverplate/domain/UserPhysical.java
Labels: enhancement

#7 Refactor/6
  build.gradle
  src/main/java/com/plate/silverplate/SilverPlateApplication.java
  src/main/java/com/plate/silverplate/battle/domain/entity/Battle.java
  src/main/java/com/plate/silverplate/battle/domain/entity/BattleHistory.java
  src/main/java/com/plate/silverplate/config/JpaAuditingConfig.java
  src/main/java/com/plate/silverplate/domain/NutritionFact.java
  src/main/java/com/plate/silverplate/foodRegistration/domain/entity/FoodRegistration.java
  src/main/java/com/plate/silverplate/meal/domain/entity/Favorite.java
  src/main/java/com/plate/silverplate/meal/domain/entity/Meal.java
  src/main/java/com/plate/silverplate/meal/domain/entity/MealList.java
  src/main/java/com/plate/silverplate/mealDailyScore/domain/entity/MealDailyScore.java
  src/main/java/com/plate/silverplate/nutritionFact/domain/entity/NutritionFact.java
  src/main/java/com/plate/silverplate/registration/domain/entity/Registration.java
  src/main/java/com/plate/silverplate/user/domain/entity/User.java
  src/main/java/com/plate/silverplate/userPhysical/domain/entity/UserPhysical.java
Labels: 🔨 Refactor

#8 Feat : 공공데이터 포털 데이터 수집
  build.gradle
  src/main/java/com/plate/silverplate/common/exception/ErrorCode.java
  src/main/java/com/plate/silverplate/common/exception/ErrorException.java
  src/main/java/com/plate/silverplate/common/exception/ErrorResponse.java
  src/main/java/com/plate/silverplate/common/exception/GlobalExceptionHandler.java
  src/main/java/com/plate/silverplate/nutritionFact/domain/entity/NutritionFact.java
  src/main/java/com/plate/silverplate/nutritionFact/domain/repo/NutritionFactRepository.java
  src/main/java/com/plate/silverplate/nutritionFact/dto/response/NutritionFactResponse.java
  src/main/java/com/plate/silverplate/nutritionFact/service/NutritionFactService.java
  src/main/resources/application.yml
Labels: ✨ Feature

#11 feat : 카카오 로그인 구현
  build.gradle
  src/main/java/com/plate/silverplate/config/SecurityConfig.java
  src/main/java/com/plate/silverplate/user/controller/OauthController.java
  src/main/java/com/plate/silverplate/user/domain/dto/KakaoUserInfo.java
  src/main/java/com/plate/silverplate/user/domain/dto/LoginResponse.java
  src/main/java/com/plate/silverplate/user/domain/dto/Oauth2UserInfo.java
  src/main/java/com/plate/silverplate/user/domain/dto/OauthTokenResponse.java
  src/main/java/com/plate/silverplate/user/domain/entity/Role.java
  src/main/java/com/plate/silverplate/user/domain/entity/User.java
  src/main/java/com/plate/silverplate/user/domain/entity/UserProfile.java
  src/main/java/com/plate/silverplate/user/jwt/JwtTokenProvider.java
  src/main/java/com/plate/silverplate/user/repository/UserRepository.java
  src/main/java/com/plate/silverplate/user/service/OauthService.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: ✨ Feature
