Repository silver-plate/SilverPlate-BE, pull requests merged in 2024-01, with the labels that each got.

#19 feat: 카카오 로그인 로직 변경
  build.gradle
  src/main/java/com/plate/silverplate/common/exception/ErrorCode.java
  src/main/java/com/plate/silverplate/common/exception/MyAuthenticationFailureHandler.java
  src/main/java/com/plate/silverplate/common/exception/MyAuthenticationSuccessHandler.java
  src/main/java/com/plate/silverplate/config/SecurityConfig.java
  src/main/java/com/plate/silverplate/user/domain/dto/GeneratedToken.java
  src/main/java/com/plate/silverplate/user/domain/dto/KakaoUserInfo.java
  src/main/java/com/plate/silverplate/user/domain/dto/LoginResponse.java
  src/main/java/com/plate/silverplate/user/domain/dto/OAuth2Attribute.java
  src/main/java/com/plate/silverplate/user/domain/dto/Oauth2UserInfo.java
  src/main/java/com/plate/silverplate/user/domain/dto/OauthTokenResponse.java
  src/main/java/com/plate/silverplate/user/domain/entity/Role.java
  src/main/java/com/plate/silverplate/user/domain/entity/User.java
  src/main/java/com/plate/silverplate/user/domain/entity/UserProfile.java
  src/main/java/com/plate/silverplate/user/jwt/JwtTokenProvider.java
  src/main/java/com/plate/silverplate/user/jwt/fillter/JwtAuthFilter.java
  src/main/java/com/plate/silverplate/user/jwt/fillter/JwtExceptionFilter.java
  src/main/java/com/plate/silverplate/user/jwt/utill/JwtUtil.java
  src/main/java/com/plate/silverplate/user/repository/UserRepository.java
  src/main/java/com/plate/silverplate/user/service/OauthService.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: ✨ Feature

#21 Refactor : 데이터 수집 api
  build.gradle
  src/main/java/com/plate/silverplate/config/RestTemplateConfig.java
  src/main/java/com/plate/silverplate/nutritionFact/domain/repo/NutritionFactRepository.java
  src/main/java/com/plate/silverplate/nutritionFact/service/NutritionFactService.java
Labels: 🔨 Refactor

#23 feat : 카카오 로그인 추가 구현
  src/main/java/com/plate/silverplate/common/exception/MyAuthenticationFailureHandler.java
  src/main/java/com/plate/silverplate/common/exception/MyAuthenticationSuccessHandler.java
  src/main/java/com/plate/silverplate/config/RedisConfig.java
  src/main/java/com/plate/silverplate/config/SecurityConfig.java
  src/main/java/com/plate/silverplate/user/controller/UserController.java
  src/main/java/com/plate/silverplate/user/domain/dto/GeneratedToken.java
  src/main/java/com/plate/silverplate/user/domain/dto/LoginResponse.java
  src/main/java/com/plate/silverplate/user/domain/dto/OAuth2Attribute.java
  src/main/java/com/plate/silverplate/user/domain/dto/TokenRequest.java
  src/main/java/com/plate/silverplate/user/domain/dto/TokenResponse.java
  src/main/java/com/plate/silverplate/user/domain/entity/User.java
  src/main/java/com/plate/silverplate/user/domain/entity/UserProfile.java
  src/main/java/com/plate/silverplate/user/jwt/fillter/JwtAuthFilter.java
  src/main/java/com/plate/silverplate/user/jwt/utill/JwtUtil.java
  src/main/java/com/plate/silverplate/user/repository/UserProfileRepository.java
  src/main/java/com/plate/silverplate/user/repository/UserRepository.java
  src/main/java/com/plate/silverplate/user/service/OauthService.java
  src/main/java/com/plate/silverplate/user/service/RedisService.java
  src/main/java/com/plate/silverplate/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: 🔨 Refactor, ✨ Feature

#26 feat: 유저 신체정보 생성 api
  src/main/java/com/plate/silverplate/common/exception/GlobalExceptionHandler.java
  src/main/java/com/plate/silverplate/config/SecurityConfig.java
  src/main/java/com/plate/silverplate/user/controller/UserController.java
  src/main/java/com/plate/silverplate/user/domain/entity/User.java
  src/main/java/com/plate/silverplate/user/domain/entity/UserProfile.java
  src/main/java/com/plate/silverplate/user/jwt/fillter/JwtAuthFilter.java
  src/main/java/com/plate/silverplate/user/jwt/utill/JwtUtil.java
  src/main/java/com/plate/silverplate/userPhysical/controller/UserPhysicalController.java
  src/main/java/com/plate/silverplate/userPhysical/domain/dto/UserPhysicalRequest.java
  src/main/java/com/plate/silverplate/userPhysical/domain/entity/Gender.java
  src/main/java/com/plate/silverplate/userPhysical/domain/entity/UserPhysical.java
  src/main/java/com/plate/silverplate/userPhysical/repository/UserPhysicalRepository.java
  src/main/java/com/plate/silverplate/userPhysical/service/UserPhysicalService.java
Labels: ✨ Feature, 🐞 BugFix

#28 feat: SuccessHandler 응답 데이터 형식 변경
  src/main/java/com/plate/silverplate/common/exception/MyAuthenticationSuccessHandler.java
  src/main/java/com/plate/silverplate/user/jwt/fillter/JwtAuthFilter.java
  src/main/java/com/plate/silverplate/user/jwt/utill/JwtUtil.java
  src/main/java/com/plate/silverplate/user/service/OauthService.java
Labels: 🔨 Refactor, ✨ Feature

#30 Feat : 한끼 등록 Api 추가 및 스웨거 설정
  build.gradle
  src/main/java/com/plate/silverplate/common/exception/ErrorCode.java
  src/main/java/com/plate/silverplate/config/OpenApiConfig.java
  src/main/java/com/plate/silverplate/config/RestTemplateConfig.java
  src/main/java/com/plate/silverplate/config/SecurityConfig.java
  src/main/java/com/plate/silverplate/meal/controller/MealController.java
  src/main/java/com/plate/silverplate/meal/domain/entity/Favorite.java
  src/main/java/com/plate/silverplate/meal/domain/entity/Meal.java
  src/main/java/com/plate/silverplate/meal/domain/entity/MealList.java
  src/main/java/com/plate/silverplate/meal/domain/repository/MealListRepository.java
  src/main/java/com/plate/silverplate/meal/domain/repository/MealRepository.java
  src/main/java/com/plate/silverplate/meal/dto/request/MealCreateRequest.java
  src/main/java/com/plate/silverplate/meal/dto/request/MealListCreateRequest.java
  src/main/java/com/plate/silverplate/meal/dto/response/MealCreateResponse.java
  src/main/java/com/plate/silverplate/meal/service/MealService.java
  src/main/java/com/plate/silverplate/nutritionFact/service/NutritionFactService.java
Labels: ✨ Feature

#32 fix: redis 관련 환경변수가 적용되지 않는 문제 해결
  src/main/java/com/plate/silverplate/config/RedisConfig.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#33 feat: 신체 정보 수정, 기존 정보 조회 api
  src/main/java/com/plate/silverplate/common/exception/ErrorCode.java
  src/main/java/com/plate/silverplate/user/domain/entity/User.java
  src/main/java/com/plate/silverplate/userPhysical/controller/UserPhysicalController.java
  src/main/java/com/plate/silverplate/userPhysical/domain/dto/request/UserPhysicalRequest.java
  src/main/java/com/plate/silverplate/userPhysical/domain/dto/response/UserPhysicalCreateResponse.java
  src/main/java/com/plate/silverplate/userPhysical/domain/dto/response/UserPhysicalResponse.java
  src/main/java/com/plate/silverplate/userPhysical/domain/entity/UserPhysical.java
  src/main/java/com/plate/silverplate/userPhysical/repository/UserPhysicalRepository.java
  src/main/java/com/plate/silverplate/userPhysical/service/UserPhysicalService.java
Labels: 🔨 Refactor, ✨ Feature
